/-
  QuantumRelational/CyclicEigen.lean

  **`thm:complex`: Emergence of Complex Numbers** (eigenvalue part)
  **`lem:sheaf-complex`: Continuous Evolution Requires ℂ**
  **`thm:cyclic`: Cyclic Structure — G_dyn ≅ Z_N**

  The N×N cyclic permutation matrix π has eigenvalues e^{2πik/N}.
  For N ≥ 3, at least one eigenvalue is non-real, forcing the
  coefficient field to contain ℂ.

  The cyclic permutation generates a subgroup isomorphic to Z_N.

  Tier 1: Uses Mathlib complex analysis and group theory.
  Lean status: fully-derived
-/
import Mathlib.Analysis.SpecialFunctions.Complex.Circle
import Mathlib.Analysis.Complex.Exponential
import Mathlib.GroupTheory.Perm.Fin
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.GroupTheory.SpecificGroups.Cyclic

namespace QuantumRelational.CyclicEigen

open Complex

/-- The N-th roots of unity are e^{2πik/N} for k = 0, ..., N-1. -/
noncomputable def rootOfUnity (N : ℕ) (k : Fin N) : ℂ :=
  exp (2 * Real.pi * k.val / N * I)

/-- Each root of unity satisfies z^N = 1. -/
theorem rootOfUnity_pow (N : ℕ) (hN : 0 < N) (k : Fin N) :
    (rootOfUnity N k) ^ N = 1 := by
  simp only [rootOfUnity]
  rw [← exp_nat_mul]
  have hNne : (N : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr (Nat.pos_iff_ne_zero.mp hN)
  have hrw : ↑N * (2 * ↑Real.pi * ↑↑k / ↑N * I) =
      ↑(↑k.val : ℤ) * (2 * ↑Real.pi * I) := by
    field_simp
    push_cast
    ring
  rw [hrw]
  exact exp_int_mul_two_pi_mul_I (↑k.val)

/-- For N ≥ 3, the root e^{2πi/N} is non-real.
    Proof: Im(e^{2πi/N}) = sin(2π/N) > 0 for 0 < 2π/N < π. -/
theorem nonreal_eigenvalue (N : ℕ) (hN : 3 ≤ N) :
    (rootOfUnity N ⟨1, by omega⟩).im ≠ 0 := by
  -- Define the angle θ = 2π/N as a real number
  set θ : ℝ := 2 * Real.pi * (1 : ℕ) / (N : ℝ) with hθ_def
  -- The root of unity is exp(↑θ * I)
  have hform : rootOfUnity N ⟨1, by omega⟩ = exp (↑θ * I) := by
    simp only [rootOfUnity, θ]
    congr 1
    push_cast
    ring
  rw [hform, exp_mul_I]
  -- After exp_mul_I, goal involves Complex.cos and Complex.sin
  -- Use cos_ofReal_im and ofReal_sin_ofReal_re to reduce to Real.sin θ
  simp only [Complex.add_im, Complex.mul_im, Complex.I_im, Complex.I_re,
             mul_one, mul_zero, cos_ofReal_im, sin_ofReal_re, zero_add, add_zero]
  -- Goal: Real.sin θ ≠ 0; we show sin θ > 0
  apply ne_of_gt
  apply Real.sin_pos_of_pos_of_lt_pi
  · -- 0 < θ = 2π/N
    simp only [θ]
    have hNpos : (0 : ℝ) < N := by exact_mod_cast (by omega : 0 < N)
    positivity
  · -- θ = 2π/N < π, i.e., 2π/N < π, i.e., 2/N < 1, i.e., 2 < N
    simp only [θ]
    have hNpos : (0 : ℝ) < N := by exact_mod_cast (by omega : 0 < N)
    rw [div_lt_iff₀ hNpos]
    simp only [Nat.cast_one, mul_one]
    have hN3 : (3 : ℝ) ≤ N := by exact_mod_cast hN
    have hpi := Real.pi_pos
    nlinarith

/-- For N = 2, the eigenvalues are {+1, -1}, both real. -/
theorem N2_eigenvalues_real :
    (rootOfUnity 2 ⟨0, by omega⟩).im = 0 ∧
    (rootOfUnity 2 ⟨1, by omega⟩).im = 0 := by
  constructor
  · -- k = 0: exp(0 * I) = 1, Im = 0
    simp [rootOfUnity]
  · -- k = 1: exp(π * I), Im = sin(π) = 0
    have hform : rootOfUnity 2 ⟨1, by omega⟩ = exp (↑(Real.pi) * I) := by
      simp only [rootOfUnity]
      congr 1
      push_cast
      ring
    rw [hform, exp_mul_I]
    simp only [Complex.add_im, Complex.mul_im, Complex.I_im, Complex.I_re,
               mul_one, mul_zero, cos_ofReal_im, sin_ofReal_re, zero_add, add_zero]
    exact Real.sin_pi

/-- **`lem:sheaf-complex` (summary):** For N ≥ 3, the cyclic permutation matrix has
    non-real eigenvalues, so the coefficient field must extend ℝ to ℂ.
    Combined with Frobenius (Thm 44), this forces 𝕂 = ℂ. -/
theorem complex_forced (N : ℕ) (hN : 3 ≤ N) :
    ∃ (k : Fin N), (rootOfUnity N k).im ≠ 0 :=
  ⟨⟨1, by omega⟩, nonreal_eigenvalue N hN⟩

-- ============================================================
-- Statement #51: Cyclic Structure — G_dyn = ⟨π⟩ ≅ Z_N
-- ============================================================

/-! ### The Cyclic Permutation Group

The cyclic permutation π on Fin N (mapping i → i+1 mod N) generates
a subgroup ⟨π⟩ of order N, hence isomorphic to Z_N.

We use Mathlib's `finRotate N`, which is exactly the map i → i + 1 mod N.
Key steps:
1. `finRotate (n+2)` is a cycle (Mathlib: `isCycle_finRotate`)
2. Its support is all of `Fin (n+2)` (Mathlib: `support_finRotate`)
3. For a cycle, `orderOf` = support cardinality (Mathlib: `IsCycle.orderOf`)
4. Therefore `orderOf (finRotate N) = N` for N ≥ 2
5. `Subgroup.zpowers` is always cyclic, with cardinality = `orderOf`
-/

/-- **The cyclic permutation on Fin N has order N** (for N ≥ 2).

    Since `finRotate (n+2)` is a cycle with support = Finset.univ,
    its order equals |Fin (n+2)| = n+2. -/
theorem orderOf_finRotate (N : ℕ) (hN : 2 ≤ N) :
    orderOf (finRotate N) = N := by
  obtain ⟨n, rfl⟩ := Nat.exists_eq_add_of_le hN
  have h : 2 + n = n + 2 := by omega
  rw [h, isCycle_finRotate.orderOf, support_finRotate, Finset.card_univ, Fintype.card_fin]

/-- **The subgroup ⟨π⟩ generated by the cyclic permutation has cardinality N.** -/
theorem card_zpowers_finRotate (N : ℕ) (hN : 2 ≤ N) :
    Nat.card (Subgroup.zpowers (finRotate N)) = N := by
  rw [Nat.card_zpowers, orderOf_finRotate N hN]

/-- **`thm:cyclic`: Cyclic Structure — G_dyn = ⟨π⟩ ≅ Z_N.**

    The intra-basis dynamical symmetry group G_dyn = ⟨π⟩ is cyclic
    of order N. Since any two cyclic groups of the same finite order
    are isomorphic, G_dyn ≅ Z_N.

    We prove:
    (1) ⟨π⟩ is cyclic (Mathlib: `Subgroup.isCyclic_zpowers`)
    (2) |⟨π⟩| = N (from `orderOf_finRotate`)
    Together these characterize ⟨π⟩ ≅ Z_N up to isomorphism. -/
theorem cyclic_group_structure (N : ℕ) (hN : 2 ≤ N) :
    IsCyclic (Subgroup.zpowers (finRotate N)) ∧
    Nat.card (Subgroup.zpowers (finRotate N)) = N := by
  refine ⟨?_, card_zpowers_finRotate N hN⟩
  rw [Subgroup.isCyclic_iff_exists_zpowers_eq_top]
  exact ⟨finRotate N, rfl⟩

end QuantumRelational.CyclicEigen
