#!/usr/bin/env python3
"""
dep_graph.py — Lean formalization dependency graph extractor.

Scans all .lean files in QuantumRelational/ and produces:
1. A module-level dependency graph (which file imports which)
2. A list of theorems/lemmas/defs per file
3. A report of imported classical axioms and where they're used

Outputs:
  - scripts/DEPENDENCY_REPORT.md  (human-readable markdown)
  - scripts/dep_graph.dot         (Graphviz DOT format for visualization)

Usage:
  python3 scripts/dep_graph.py
"""

import re
import sys
from pathlib import Path
from collections import defaultdict


SCRIPT_DIR = Path(__file__).parent
ROOT = SCRIPT_DIR.parent
LEAN_DIR = ROOT / "QuantumRelational"

# Regexes
IMPORT_RE = re.compile(r'^\s*import\s+(QuantumRelational\.[\w.]+)', re.MULTILINE)
# Declarations must start at column 0 (top-level) and be one of the standard keywords.
DECL_RE = re.compile(
    r'^(theorem|lemma|def|structure|abbrev|axiom|noncomputable\s+def|noncomputable\s+theorem|noncomputable\s+abbrev)\s+(\S+)',
    re.MULTILINE,
)
# Axioms: must be at column 0 (not inside comments or docs).
AXIOM_DECL_RE = re.compile(r'^axiom\s+(\S+)', re.MULTILINE)


def module_name(path: Path) -> str:
    """Convert .lean path to Lean module name."""
    rel = path.relative_to(ROOT).with_suffix("")
    return str(rel).replace("/", ".")


def strip_block_comments(text: str) -> str:
    """Remove Lean block comments /- ... -/ (including docstrings /-- ... -/)."""
    # Match /- ... -/ non-greedy, possibly nested? Lean allows nesting so we
    # approximate by removing outer pairs; most of our files don't nest.
    result = []
    i = 0
    depth = 0
    while i < len(text):
        if text[i:i+2] == "/-":
            depth += 1
            i += 2
        elif text[i:i+2] == "-/" and depth > 0:
            depth -= 1
            i += 2
        elif depth > 0:
            i += 1
        else:
            result.append(text[i])
            i += 1
    return "".join(result)


def extract_info(path: Path):
    """Extract imports, declarations, and axioms from a .lean file."""
    text = path.read_text(encoding="utf-8")
    # Imports are extracted from the raw text (they can appear before block comments).
    imports = IMPORT_RE.findall(text)
    # For decls and axioms, strip block comments to avoid matching commented text.
    clean = strip_block_comments(text)
    decls = DECL_RE.findall(clean)
    axioms = AXIOM_DECL_RE.findall(clean)
    # Strip keyword artifacts from decls (noncomputable def capture)
    decl_list = []
    for kw, name in decls:
        kw = kw.strip().replace("noncomputable", "").strip() or "def"
        decl_list.append((kw, name))
    return imports, decl_list, axioms


def main():
    files = sorted(LEAN_DIR.rglob("*.lean"))
    module_info = {}
    for p in files:
        name = module_name(p)
        imports, decls, axioms = extract_info(p)
        module_info[name] = {
            "path": p.relative_to(ROOT),
            "imports": imports,
            "decls": decls,
            "axioms": axioms,
        }

    # Build module-level dep graph
    dep_graph = defaultdict(set)
    for m, info in module_info.items():
        for imp in info["imports"]:
            dep_graph[m].add(imp)

    # Write Markdown report
    md_path = SCRIPT_DIR / "DEPENDENCY_REPORT.md"
    with md_path.open("w", encoding="utf-8") as f:
        f.write("# Lean Formalization — Dependency Report\n\n")
        f.write(
            "Auto-generated by `scripts/dep_graph.py`. "
            "Last run: run the script to update this file.\n\n"
        )
        f.write(f"**Total files:** {len(module_info)}\n\n")

        total_decls = sum(len(info["decls"]) for info in module_info.values())
        total_theorems = sum(
            sum(1 for kw, _ in info["decls"] if kw in ("theorem", "lemma"))
            for info in module_info.values()
        )
        total_axioms = sum(len(info["axioms"]) for info in module_info.values())
        f.write(f"**Total declarations:** {total_decls}\n\n")
        f.write(f"**Theorems/lemmas:** {total_theorems}\n\n")
        f.write(f"**Axioms declared:** {total_axioms}\n\n")

        f.write("## Module Dependency Graph\n\n")
        f.write(
            "Each row lists a module and the QuantumRelational modules "
            "it directly imports. (Mathlib and external imports are omitted.)\n\n"
        )
        f.write("| Module | Imports |\n|--------|---------|\n")
        for m in sorted(module_info):
            imports = sorted(module_info[m]["imports"])
            if imports:
                f.write(f"| `{m}` | {', '.join(f'`{i}`' for i in imports)} |\n")
            else:
                f.write(f"| `{m}` | (no QuantumRelational imports) |\n")
        f.write("\n")

        f.write("## Axioms Declared\n\n")
        f.write(
            "All axioms in the formalization, listed by module. "
            "Each should correspond to a classical result cited in the paper.\n\n"
        )
        any_axioms = False
        for m in sorted(module_info):
            axioms = module_info[m]["axioms"]
            if axioms:
                any_axioms = True
                f.write(f"### `{m}`\n\n")
                for a in axioms:
                    f.write(f"- `{a}`\n")
                f.write("\n")
        if not any_axioms:
            f.write("(no axioms found)\n\n")

        f.write("## Declarations per Module\n\n")
        for m in sorted(module_info):
            info = module_info[m]
            decls = info["decls"]
            if not decls:
                continue
            f.write(f"### `{m}`\n\n")
            f.write(f"File: `{info['path']}`\n\n")
            kw_counts = defaultdict(int)
            for kw, _ in decls:
                kw_counts[kw] += 1
            f.write("Summary: " + ", ".join(
                f"{n} {kw}" for kw, n in sorted(kw_counts.items())
            ) + "\n\n")
            f.write("<details><summary>Declarations</summary>\n\n")
            for kw, name in decls:
                f.write(f"- `{kw} {name}`\n")
            f.write("\n</details>\n\n")

    # Write Graphviz DOT
    dot_path = SCRIPT_DIR / "dep_graph.dot"
    with dot_path.open("w", encoding="utf-8") as f:
        f.write("digraph QuantumRelational {\n")
        f.write("  rankdir=BT;\n")
        f.write("  node [shape=box, style=rounded, fontname=Helvetica];\n")
        f.write("  edge [color=gray50];\n")
        for m in sorted(module_info):
            short = m.replace("QuantumRelational.", "")
            f.write(f'  "{short}";\n')
        for m, imports in sorted(dep_graph.items()):
            short_m = m.replace("QuantumRelational.", "")
            for imp in sorted(imports):
                short_i = imp.replace("QuantumRelational.", "")
                f.write(f'  "{short_m}" -> "{short_i}";\n')
        f.write("}\n")

    print(f"Wrote {md_path.relative_to(ROOT)}")
    print(f"Wrote {dot_path.relative_to(ROOT)}")
    print(f"To render DOT:")
    print(f"  dot -Tsvg {dot_path.relative_to(ROOT)} -o scripts/dep_graph.svg")
    print(f"Summary:")
    print(f"  {len(module_info)} files")
    print(f"  {total_decls} declarations ({total_theorems} theorems/lemmas)")
    print(f"  {total_axioms} axioms")


if __name__ == "__main__":
    main()
